# Trabalho Prático Parte 1

In [1]:
import numpy as np
import math

## Questão 1

Calcule as abscissas $t_i$ e os pesos $w_i$ via a matriz de Jacobi.

In [2]:
# YOUR CODE HERE
def jacobi(n):    
    
    # Iniciar a matriz J
    J = np.zeros((n,n))
    for i in range(1, n):
            J[i][i-1] = np.sqrt((i**2)/(4*(i**2)-1))
            J[i-1][i] = np.sqrt((i**2)/(4*(i**2)-1))
            
    # Calcular autovalores e autovetores
    t, a_vetores = np.linalg.eig(J)
    
    v = a_vetores[0,:]
    
    # Ordenar em ordem decrescente do autovalor
    matriz_t_v = np.vstack((t, v))
    ordena_matriz = matriz_t_v[:, matriz_t_v[0].argsort()[::-1]]
    
    t = ordena_matriz[0, :]
    
    # Calcular w
    w = 2 * (ordena_matriz[1,:])**2
        
    # Retornar t e w como vetores de dimensões 1 x n
    return t, w

    #raise NotImplementedError()

In [3]:
ans2 = ([ 0.57735027, -0.57735027], [0.9999999999999998, 0.9999999999999998])
ans3 = ([ 7.74596669e-01, -4.78946310e-17, -7.74596669e-01], [0.5555555555555551, 0.8888888888888894, 0.5555555555555556])
ans4 = ([ 0.86113631,  0.33998104, -0.33998104, -0.86113631], [0.3478548451374544, 0.652145154862546, 0.6521451548625463, 0.3478548451374541])
assert np.allclose(ans2, jacobi(2))
assert np.allclose(ans3, jacobi(3))
assert np.allclose(ans4, jacobi(4))

Inicie os vetores ```difTab2```, ```difTab3``` e ```difTab4``` com as diferenças entre os $t$s e $w$s encontrados para $n=2,3,4$ com os valores tabelados.

In [4]:
#difTab3[0][0] guarda t[0] - t0 tabelado pra n=3
#difTab3[0][1] guarda t[1] - t1 tabelado pra n=3
#difTab3[0][2] guarda t[2] - t2 tabelado pra n=3
#
#difTab3[1][0] guarda w[0] - w0 tabelado pra n=3
#difTab3[1][1] guarda w[1] - w1 tabelado pra n=3
#difTab3[1][2] guarda w[2] - w2 tabelado pra n=3
#...

# YOUR CODE HERE
t2, w2 = jacobi(2)
t3, w3 = jacobi(3)
t4, w4 = jacobi(4)

tab_t2 = np.array([0.5773502692, -0.5773502692])
tab_w2 = np.array([1., 1.])
tab_t3 = np.array([0.7745966692, 0, -0.7745966692])
tab_w3 = np.array([0.5555555556, 0.8888888889, 0.5555555556])
tab_t4 = np.array([0.8611363116, 0.3399810436, -0.3399810436, -0.8611363116])
tab_w4 = np.array([0.3478548451, 0.6521451549,  0.6521451549, 0.3478548451])

difTab2 = np.zeros((2,2))
difTab2[0, :] = t2 - tab_t2
difTab2[1, :] = w2 - tab_w2

difTab3 = np.zeros((2,3))
difTab3[0, :] = t3 - tab_t3
difTab3[1, :] = w3 - tab_w3

difTab4 = np.zeros((2,4))
difTab4[0, :] = t4 - tab_t4
difTab4[1, :] = w4 - tab_w4

#raise NotImplementedError()

In [5]:
print("difTab2: ", difTab2, "\n")
print("difTab3: ", difTab3, "\n")
print("difTab4: ", difTab4, "\n")

difTab2:  [[-1.03742570e-11  1.03742570e-11]
 [-2.22044605e-16 -2.22044605e-16]] 

difTab3:  [[ 4.14832613e-11 -4.78946310e-17 -4.14834833e-11]
 [-4.44448922e-11 -1.11105569e-11 -4.44444481e-11]] 

difTab4:  [[-5.94757577e-12 -1.51436086e-11  1.51437196e-11  5.94713168e-12]
 [ 3.74544284e-11 -3.74540399e-11 -3.74537068e-11  3.74541509e-11]] 



## Questão 2

In [6]:
print(jacobi(2))
print(jacobi(3))
print(jacobi(4))

(array([ 0.57735027, -0.57735027]), array([1., 1.]))
(array([ 7.74596669e-01, -4.78946310e-17, -7.74596669e-01]), array([0.55555556, 0.88888889, 0.55555556]))
(array([ 0.86113631,  0.33998104, -0.33998104, -0.86113631]), array([0.34785485, 0.65214515, 0.65214515, 0.34785485]))


Porque para $n=2,3,4$ a soma dos pesos é igual a 2?

#YOUR ANSWER HERE

Para descobrir a soma dos pesos pela fórmula da Quadratura, assumimos f(xi) = 1 no intervalo de integração [-1, 1].Teremos então apenas o somatório de wi, de 0 a n.
Daí a regra da Quadratura de Gauss passa a ser a integral de 1 entre [-1, 1] (que vale 2).

## Questão 3

Escreva uma função para calcular a integral pela quadratura de Gauss-Legendre.

In [7]:
# y é um vetor 1 x n em que y[i]=f(x[i])
# w é o vetor 1 x n obtido com a função jacobi

# YOUR CODE HERE
def gaussLegendre(y, n, a, b, w):
    I = 0
    for i in range(n):
        I += w[i] * y[i]
        
    I *= ((b-a)/2)
    
    return I

#raise NotImplementedError()

Calcule $\int_0^2(x^5-x^3+x-1)dx$ usando $n=2$ na função de Gauss-Legendre que você criou.

In [8]:
#intGL2 = 

# YOUR CODE HERE
t, w = jacobi(2)
f = lambda x: eval("x**5 - x**3 + x - 1")
x_i = t + 1
y = f(x_i)

intGL2 = gaussLegendre(y, 2, 0, 2, w)

#raise NotImplementedError()

In [9]:
assert np.isclose(5.777777777777776, intGL2)

Calcule $\int_0^2(x^5-x^3+x-1)dx$ usando $n=3$ na função de Gauss-Legendre que você criou.

In [10]:
#intGL3 = 

# YOUR CODE HERE
t, w = jacobi(3)
f = lambda x: eval("x**5 - x**3 + x - 1")
x_i = t + 1
y = f(x_i)

intGL3 = gaussLegendre(y, 3, 0, 2, w)

#raise NotImplementedError()

In [11]:
assert np.isclose(6.6666666666666625, intGL3)

Calcule $\int_0^2(x^5-x^3+x-1)dx$ usando $n=4$ na função de Gauss-Legendre que você criou.

In [12]:
#intGL4 = 

# YOUR CODE HERE
t, w = jacobi(4)
f = lambda x: eval("x**5 - x**3 + x - 1")
x_i = t + 1
y = f(x_i)

intGL4 = gaussLegendre(y, 4, 0, 2, w)

#raise NotImplementedError()

In [13]:
assert np.isclose(6.666666666666674, intGL4)

Explique os resultados obtidos para $\int_0^2 (x^5-x^3+x-1) dx$ com $n = 2,3,4$.

#YOUR ANSWER HERE

Como o polinômio original possui grau 5, cada vez que aumentamos n no cálculo, o grau (n) se aproxima do grau do polinômio original. Assim teremos resultados cada vez mais precisos (conforme n se aproxima de 5).

## Questão 4

Qual o valor exato de $\int_0^\pi \sin(x) dx$?

In [14]:
#exact = 

# YOUR CODE HERE

derivative = lambda x: eval("- np.cos(x)")
exact = derivative(np.pi) - derivative(0)

#raise NotImplementedError()

Inicie o vetor ```difExac``` com as diferenças entre os valores encontrados para $n=3,4,5$ e o valor exato.

In [15]:
#difExac[0] guarda exact - resultado pra n=3
#difExac[1] guarda exact - resultado pra n=4
#difExac[2] guarda exact - resultado pra n=5
#difExac =

# YOUR CODE HERE
difExac = []

f = lambda x: eval("np.sin(x)")

t, w = jacobi(3)
x_i = 0 + (np.pi-0)*(t+1)/2
y = f(x_i)
n3_result = gaussLegendre(y, 3, 0, np.pi, w)

difExac.append(exact - n3_result)

t, w = jacobi(4)
x_i = 0 + (np.pi-0)*(t+1)/2
y = f(x_i)
n4_result = gaussLegendre(y, 4, 0, np.pi, w)

difExac.append(exact - n4_result)

t, w = jacobi(5)
x_i = 0 + (np.pi-0)*(t+1)/2
y = f(x_i)
n5_result = gaussLegendre(y, 5, 0, np.pi, w)

difExac.append(exact - n5_result)

#raise NotImplementedError()

In [16]:
print(difExac)

[-0.001388913607744069, 1.577154227838662e-05, -1.102844717770779e-07]


## Questão 5

Seja $f(x)=e^x$. Avalie $f(x)$ em $x_0=-\frac{\sqrt{3}}{3}$ e $x_1=\frac{\sqrt{3}}{3}$.

In [17]:
#y[0] guarda f(x0)
#y[1] guarda f(x1)
#y = 

# YOUR CODE HERE
y = []
f = lambda x: eval("np.e**x")
y.append(f(-np.sqrt(3)/3))
y.append(f(np.sqrt(3)/3))

#raise NotImplementedError()

In [18]:
print(y)

[0.5613839137989282, 1.7813121741108022]


Determine o polinômio linear $p(x)$ que passa pelos pontos ($x_0$,y[0]) e ($x_1$,y[1]).

In [19]:
#p[0] guarda o coeficiente de x^0
#p[1] guarda o coeficiente de x^1
#p = 

# YOUR CODE HERE
a = (-np.sqrt(3)/3, y[0])
b = (np.sqrt(3)/3, y[1])

A = np.array([[1, a[0]],
             [1, b[0]]])

b = np.array([[a[1]], 
             [b[1]]])

p = np.linalg.solve(A, b)

#raise NotImplementedError()

In [20]:
print(p)

[[1.17134804]
 [1.05648886]]


Calcule analiticamente $\int_{-1}^1p(x)dx$.

In [21]:
#integAn =

# YOUR CODE HERE
integAn = p[0] - (-p[0]) + p[1]*(1/2) - p[1]*(1/2)

#raise NotImplementedError()

Agora calcule $\int_{-1}^1e^xdx$ usando $n=2$ na função de Gauss-Legendre que você criou.

In [22]:
#integGL =

# YOUR CODE HERE
t, w = jacobi(2)
x_i = -1 + (1 - (-1))*(t+1)/2
f = lambda x: eval("np.e**x")
y = f(x_i)
integGL = gaussLegendre(y, 2, -1, 1, w)

#raise NotImplementedError()

In [23]:
print(integGL - integAn)

[-4.4408921e-16]


Explique os resultados.

#YOUR ANSWER HERE

Usamos os mesmo pontos das abscissas t0 e t1 pra a interpolação P(x). Dessa forma o erro encontado será pequeno, tendo em vista que o polinômio interpolador é uma aproximação da quadratura para a função original fornecida.